### ISSUE TITLE
Refreshing Data on the fly

### ISSUE THREAD

**Issue by mrtornado** [malcolm-kee/gatsby-source-mysql#1]
Hi there, I'm pretty new to gatsby, so basically I have a table with configs, and I want whenever a new entry is added to that table to rebuild gatsby, could I do this like once a minute and if I have a new entry to rebuild gatsby ? or some other method ? I control the backend too where it's a custom apollo server, could I create a hook or something in apollo server ? I have no idea how to go about this. I saw something in  gatsby-source-graphql, refetchInterval: 60,
should I try to use that instead of gatsby-source-mysql ?
 I would also like to create pages programmatically since I want to let users modify some settings in there configs, so in the database itself, I suppose the best way would be to connect directly to the database, but I need the change updated on the fly, I'm using apollo client for that but I don't know how to create pages programmatically with that approach, some guidance would be great. Thanks
 Alex

**Comment by mrtornado** [comment]
The way I'm thinking of doing this is create pages programmatically from gatsby-source-mysql and using apollo client in the page template to pull the data directly from my apollo server express that I have in the backend, but for that I would need a refetchInterval: 60 so when new clients purchase there configs should show in the client portal.

**Comment by malcolm-kee** [comment]
Hi @mrtornado , if your page need update on the fly, then you don't add them as gatsby plugin, instead your code should make an ajax request to get them when the page load like a typical React application.

Usually, the data we source via gatsby-plugin are data that are static data, e.g. content provided by content creator that will be consistent for all users. User generated content are usually handled outside from gatsby plugin.

The options for `gatsby-source-graphql` is not meant for production behavior, it's only used in development purpose only so you doesn't need to restart gatsby server manually.
