### ISSUE TITLE
Multiple Foreign keys

### ISSUE THREAD

**Issue by rekuenkdr** [malcolm-kee/gatsby-source-mysql#13]
Hi, I have several tables, with multiple foreign keys referencing other tables, would it be possible to pass 'parentName', 'foreignKey' and 'cardinality' as an array of objects?

Something like:
```js
relations: [
 {
    parentName: "table1",
    foreignKey: "table1_foreignKey",
    cardinality: "OneToOne",
 },
 {
    parentName: "table2",
    foreignKey: "table1_secondForeignKey",
    cardinality: "OneToOne",
 },
]
```
Thanks.

**Comment by malcolm-kee** [comment]
Since each query produce a Gatsby Type, you can do it yourself by link them manually.
See https://www.gatsbyjs.org/docs/schema-customization/#foreign-key-fields

**Comment by rekuenkdr** [comment]
Hi,
the question wais aimed precisely to avoid manually linking the nodes, but thanks anyway, I would fork and modify the plugin myself to sort this out, I will try to maintain the current schema to keep backwards compatibility for those who don't need this feature.

**Comment by malcolm-kee** [comment]
What you mean by manually linking them? Both needs manual configuration, it's just whether you configure with options of this plugin or using gatsby-node.js createSchemaCustomization hook.

**Comment by rekuenkdr** [comment]
The main idea is to modify the plugin, to support the relations object that I mentioned before, so it will loop through that object and create as many relations as needed, maintaining also the current schema for specifying the foreign relations so it won't broke for people using it as it is now.

So if there is only one relation per table:

```js
    parentName: "table1",
    foreignKey: "table1_foreignKey",
    cardinality: "OneToOne",
```
If there are more than one foreign key relations in the same table, use the relations object specified on my first comment.

I hope that helps to clarify what I meant, I'm trying to avoid the createSchemaCustomization hook and just modify and configure the plugin to do that automatically.

Thanks.
