### ISSUE TITLE
generating SQL?

### ISSUE THREAD

**Issue by afeld** [malcolm-kee/gatsby-source-mysql#4]
In using the plugin, it feels a bit redundant to write the query in GraphQL, and then write a superset of that query in SQL. I started looking into options for generating SQL queries based on GraphQL ones, but none were a perfect fit.

- [Graphile](https://www.graphile.org/) - right idea, but [PostgreSQL only](https://github.com/graphile/postgraphile/issues/19)
- [Prisma](https://www.prisma.io) - right idea, but currently requires Docker, cc https://github.com/prisma/prisma/issues/2992
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/) + [Gatsby GraphQL source](https://www.gatsbyjs.org/docs/third-party-graphql/) - doesn't actually generate queries for you
- [graphql-sequelize](https://github.com/mickhansen/graphql-sequelize) - right idea, but is extremely verbose

Thoughts? Maybe it's not worth the indirection?

**Comment by malcolm-kee** [comment]
Hmm.. my mental model of how the gatsby plugin works is that they need to be run before your GraphQL query can be run.

In the context of this plugin, the SQL queries you provide to this plugin will need to run first before your GraphQL can be run, so I not sure how could that be achieve.

If you have any example of gatsby plugin that could achieve something similar to what you suggest, I could have a look at how they do that.

**Comment by malcolm-kee** [comment]
@afeld by the way, does the current v2 implementation support your use case? If yes I will publish it.

**Comment by afeld** [comment]
It does, thanks!

Will investigate this issue more.

**Comment by afeld** [comment]
> my mental model of how gatsby plugins work is that they will be run to generate GraphQL types before your GraphQL query can be run

Wow...you're right! I just kind of assumed queries were passed down to `sourceNodes`, but it appears that isn't the case.

Closing, since it seems this isn't possible with Gatsby. Ah well!
