### ISSUE TITLE
Stored procedure in statement

### ISSUE THREAD

**Issue by skix123** [malcolm-kee/gatsby-source-mysql#5]
Hi, first of all - thanks for a great plugin!

It would be awesome to be able to use stored procedures in sql statement.

For example, instead of:
`statement: 'SELECT value1, value2 FROM sometable...'`

we could also use:
`statement: 'CALL someProcedure()'`

I believe that DB-related stuff should be separated from frontend and this feature would make it happen.

**Comment by malcolm-kee** [comment]
Hi @skix123 thanks for raising this issue.

I've made some changes to the plugin and it's in `v2.1.0` branch now.
Could you install that version and let me know if it works for you before I publish it?

## How to install
Use the following commands to install v2.1.0 from git:

```bash
npm install git://github.com/malcolm-kee/gatsby-source-mysql.git#v2.1.0
```

OR

```bash
yarn add git://github.com/malcolm-kee/gatsby-source-mysql.git#v2.1.0
```

## Config Changes

Update the `statement` in the options for this plugin, e.g. `statement: 'CALL yourProcedure()'`.

**Comment by skix123** [comment]
Wow that was fast! It works perfectly, thank you!
